import { Task } from './types';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Order catering for Fall orientation',
    description: 'Need to finalize headcount and dietary restrictions before sending the PO to Campus Dining.',
    category: 'Logistics',
    column: 'backlog',
    assignee: { name: 'Events Team', initials: 'ET', avatarColor: '#4d8eff' },
  },
  {
    id: '2',
    title: 'Follow up on pending sponsorships',
    description: '3 emails to potential sponsors have been unanswered for 5 days. Suggest sending a gentle reminder.',
    category: 'Logistics',
    column: 'backlog',
    assignee: { name: 'AI Suggested', initials: 'AI', avatarColor: '#a078ff' },
    isAISuggested: true,
  },
  {
    id: '3',
    title: 'Finalize Student Council Budget',
    description: 'Review phase completion required.',
    category: 'Finance',
    column: 'in_progress',
    assignee: { name: 'Treasurer', initials: 'TR', avatarColor: '#ffb4ab' },
    progress: 0.75,
    progressLabel: 'Review phase',
    dueLabel: 'Due Today',
    dueUrgent: true,
  },
  {
    id: '4',
    title: 'Review Hackathon Proposals',
    description: '8 of 12 proposals evaluated so far.',
    category: 'Review',
    column: 'in_progress',
    assignee: { name: 'Media Team', initials: 'MT', avatarColor: '#4d8eff' },
    progress: 0.66,
    progressLabel: '8/12 Evaluated',
    dueLabel: 'This week',
    dueUrgent: false,
  },
  {
    id: '5',
    title: 'Draft press release for Spring Gala',
    description: 'Approved by PR committee on Tuesday.',
    category: 'Creative',
    column: 'done',
    assignee: { name: 'PR Team', initials: 'PR', avatarColor: '#4edea3' },
    isCompleted: true,
  },
];
