import { AcademicData } from './types';

export const mockAcademicData: AcademicData = {
  semesterLabel: '2025/2026 First Semester',
  stats: {
    currentGPA: 4.2,
    targetGPA: 4.5,
    creditsCompleted: 18,
    creditsEnrolled: 24,
    totalAssignments: 14,
    completedAssignments: 9,
    studyHoursThisWeek: 22,
  },
  courses: [
    {
      id: 'c1',
      code: 'CSC 401',
      title: 'Advanced Algorithms',
      instructor: 'Prof. Adeyemi',
      credits: 4,
      currentGrade: 'A',
      gradePoint: 5.0,
      progress: 0.72,
      color: '#adc6ff',
      status: 'active',
    },
    {
      id: 'c2',
      code: 'MGT 312',
      title: 'Organizational Leadership',
      instructor: 'Dr. Okafor',
      credits: 3,
      currentGrade: 'A',
      gradePoint: 4.8,
      progress: 0.65,
      color: '#a078ff',
      status: 'active',
    },
    {
      id: 'c3',
      code: 'ECO 305',
      title: 'Public Finance & Policy',
      instructor: 'Prof. Balogun',
      credits: 3,
      currentGrade: 'B+',
      gradePoint: 4.3,
      progress: 0.55,
      color: '#4edea3',
      status: 'active',
    },
    {
      id: 'c4',
      code: 'COM 211',
      title: 'Strategic Communication',
      instructor: 'Dr. Eze',
      credits: 2,
      currentGrade: 'A',
      gradePoint: 5.0,
      progress: 0.80,
      color: '#ffb4ab',
      status: 'active',
    },
  ],
  assignments: [
    {
      id: 'a1',
      courseCode: 'CSC 401',
      title: 'Dynamic Programming Problem Set',
      dueDate: '2026-05-21',
      dueTimeLabel: 'Tomorrow, 11:59 PM',
      status: 'pending',
      priority: 'high',
      percentOfGrade: 15,
    },
    {
      id: 'a2',
      courseCode: 'MGT 312',
      title: 'Leadership Case Study Analysis',
      dueDate: '2026-05-23',
      dueTimeLabel: 'Fri, May 23',
      status: 'pending',
      priority: 'high',
      percentOfGrade: 20,
    },
    {
      id: 'a3',
      courseCode: 'ECO 305',
      title: 'Budget Proposal Draft',
      dueDate: '2026-05-25',
      dueTimeLabel: 'Sun, May 25',
      status: 'pending',
      priority: 'medium',
      percentOfGrade: 10,
    },
    {
      id: 'a4',
      courseCode: 'COM 211',
      title: 'Stakeholder Presentation',
      dueDate: '2026-05-28',
      dueTimeLabel: 'Wed, May 28',
      status: 'pending',
      priority: 'medium',
      percentOfGrade: 25,
    },
    {
      id: 'a5',
      courseCode: 'CSC 401',
      title: 'Algorithm Complexity Report',
      dueDate: '2026-05-18',
      dueTimeLabel: 'Submitted',
      status: 'submitted',
      priority: 'low',
      percentOfGrade: 10,
    },
  ],
  studyGoals: [
    { id: 'g1', label: 'CSC 401 Review', targetHours: 8, completedHours: 5 },
    { id: 'g2', label: 'MGT 312 Case Reading', targetHours: 4, completedHours: 4 },
    { id: 'g3', label: 'ECO 305 Past Papers', targetHours: 6, completedHours: 2 },
  ],
};
